### ISSUE TITLE
example error in mac

### ISSUE THREAD

**Issue by yuansliu** [GATB/gatb-core#13]
The following errors during I compile example in mac (version 10.11.6 ):

In file included from examples/debruijn/debruijn1.cpp:4:
In file included from include/gatb/gatb_core.hpp:78:
include/gatb/debruijn/impl/Graph.hpp:37:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>

command: "clang++ examples/debruijn/debruijn1.cpp -Iinclude -Llib -lgatbcore -lhdf5 -ldl -lz -lpthread  -std=c++0x -O3 -DBOOST_NO_CXX11_RVALUE_REFERENCES=1 -o debruijn1"

**Comment by pgdurand** [comment]
Can I have some details on your installation of GATB-Core ?
1. what is the release you are using ? An official one (1.x)?
2. what is the origin of your copy of GATB-Core: "git clone" or a "tar.gz" retrieved from the Releases" tab?

**Comment by yuansliu** [comment]
Thank you very much.
I download gatb-core-1.2.2-bin-Darwin from this page https://github.com/GATB/gatb-core/releases. 
And then compile the previous example.
Apple LLVM version 8.0.0 (clang-800.0.42.1). 
Maybe this version of clang has some changes about "unordered_map"?

**Comment by pgdurand** [comment]
Ok, let me check that; we already had that problem on Nov-Dec 2016, but it was fixed in the master trunk of GATB-Core source code. I'll need to get into that problem and I'll be back to you as soon as possible.

**Comment by Piezoid** [comment]
Officially <tr1/*> and std::tr1 are deprecated. But I can't find anywhere how to continue to use theses features in C++03... 

libc++ is the std implementation distributed with clang. [Here is the tr1 story with it](https://cplusplusmusings.wordpress.com/2013/06/03/whats-up-with-tr1-and-c11-and-libc/) :
> Some standard library vendors have maintained the tr1 header files for backwards compatibility. Other vendors (such as libc++, which being c++11 only, has no backwards compatibility to worry about) do not.

boost/unordered_map.hpp may be a good (drop-in) replacement ?

Edit: Oh ok, this is already handled in the code [since this commit](https://github.com/GATB/gatb-core/commit/2e9c4ad8a4d7b23c7ea5706d67f8e380847f83ba). The line numbers are different, it must be an old gatb-core version.

**Comment by yuansliu** [comment]
Tks. I get it. I can run it in linux.

**Comment by pgdurand** [comment]
ok. Otherwise, here is what you could do on OSX.

1. git clone the master trunk of gatb-core (the problem you reported is fixed in that version)
2. cd gatb-core/gatb-core
3. mkdir build ; cd build ; make -j4 package
4. you'll end up with "gatb-core-1.2.3-bin-Darwin.tar.gz" in the build directory
5. then, you can unarchive that tarball and...
6. this command should work as expected:
clang++ examples/debruijn/debruijn1.cpp -Iinclude -Llib -lgatbcore -lhdf5 -ldl -lz -lpthread  -std=c++0x -O3 -DBOOST_NO_CXX11_RVALUE_REFERENCES=1 -o debruijn1

At least, it works on my OSX system (10.10.5; clang++ 7)... ;-)

**Comment by yuansliu** [comment]
Dear all,

Very thing is ok in mac. Thank you very much for you helps. If I meet other problems during coding, please give me more helps.

Best
