### ISSUE TITLE
Changing the path where the temp files trashme_* are created

### ISSUE THREAD

**Issue by leoisl** [GATB/gatb-core#18]
Hello,

I am using GATB and creating the graph as:

`gatb::core::debruijn::impl::Graph::create("-in %s -kmer-size %d -abundance-min 0 -out %s/graph -nb-cores %d", readsFile.c_str(), kmerSize, outputFolder.c_str(), nbCores);`

However, when doing as such, some temporary files are created in the working directory:
```
            trashme_17941_cfp
            trashme_17941_debloom_partitions.h5
            trashme_17941_dsk_partitions_gatb
            trashme_17941_t2_kmers
```

I would like to create these files in a temporary folder. To do so, I looked at some parameters (especially `SortingCountAlgorithm<span>::getOptionsParser()`) and I am creating now the graph as:

`gatb::core::debruijn::impl::Graph::create("-in %s -kmer-size %d -abundance-min 0 -out %s/graph -out-tmp %s -out-dir %s -nb-cores %d", readsFile.c_str(), kmerSize, outputFolder.c_str(), tmpFolder.c_str(), tmpFolder.c_str(), nbCores);`

But this just moved the creation of `trashme_*_dsk_partitions_gatb` to the temp folder. The other files are still created in the working directory.

Is there a way of specifying a temp folder for all the trashme files?

PS:
I am still using GATB v1.2.2 in this project. If this is doable in newer version, then it is fine, I will update the GATB core version...

Thanks!

**Comment by rchikhi** [comment]
Hi! You're right, "-out-tmp" doesn't have an effect on other tempfiles apart from those for k-mer counting.
(The other files aren't as large as the DSK partitions.) I looked at the GATB code and we'd have to carry around the out-tmp variable across several classes in order to implement what you ask. 
An temp fix would be that you chdir() into a temporary folder before running Graph::create(). Would that work for you?
Rayan

**Comment by leoisl** [comment]
Hello!

Yeah, that works for me! Clean and easy!
Thanks for the answer! I am closing this issue!

++
