### ISSUE TITLE
mac compilation problem tr1

### ISSUE THREAD

**Issue by rizkg** [GATB/gatb-core#7]
compilation of MindTheGap with clang v7.3.0 does not work since commit a4438e32f3001739e87a72ff6d61f516f59db646 (19 mai), probably because of this code removed
    if (CMAKE_CXX_COMPILER_VERSION  VERSION_LESS 4.3) 
        set (dont_use_tr1 0)
    else()
        set (dont_use_tr1 1)

Should we patch gatb-core v1.2.0 for this ?

**Comment by rchikhi** [comment]
I've changed mindthegap to use USE_NEW_CXX instead of dont_use_tr1. could you try to compile it now? (update mindthegap and gatb-core). 

I'd like to deprecate dont_use_tr1 because use_new_cxx already exists

**Comment by rchikhi** [comment]
looks like the CI could compile it just now

**Comment by rizkg** [comment]
are you sure you pushed to mindthegap? i dont see any new commit. (right now mindthegap CI works because I temporarily added dont_use_tr1  variable to the cmakelist of mindthegap)

**Comment by rchikhi** [comment]
yeah, here : https://github.com/GATB/MindTheGap/commits/master

**Comment by rizkg** [comment]
oh, this does not appear in the gforge repo, did you commit to the wrong repo  :) ?

**Comment by rchikhi** [comment]
oh yes, I did :) fixed.

**Comment by rizkg** [comment]
thx, ok to switch to use_new_cxx. It seems I have to add the -DUSE_NEW_CXX in the gatb-core cmakelist.
By the way, how should we deal with such minor modif ? The politic for tools is to point to a released gatb-core submodule. Should we make a new patched gatb-core release just for this ?

**Comment by clemaitre** [comment]
Hi guys !

MindTheGap CI does not compile on mac. 
To take into account your last modifications, is it necessary to update gatb-core ? Currently I think mindthegap points to gatb-core release v1.2.0, so this is this version of gatb-core that is used in CI.

**Comment by clemaitre** [comment]
I made mindthegap point to the current master version of gatb-core (and committed it), it did not fix the problem with tr1.
Guillaume, does it compile on your mac ?

**Comment by rizkg** [comment]
I pushed a new patch in gatb-core and again made mtg point to it, CI works now.

**Comment by rizkg** [comment]
hmm, or not :)  it compiles and passes all test, but another error comes (Invalid escape sequence .), dont know what that is.

**Comment by clemaitre** [comment]
thanks ! I know what it is, I am fixing it !

**Comment by rchikhi** [comment]
@rizg:

I had added -DUSE_NEW_CXX to MindTheGap CMakefile's. It's odd that you needed to have it defined in gatb-core's CMakefile also, isn't it? Because gatb-core doesn't have any #ifdef USE_NEW_CXX.

I think our politics are to only link to a released version of gatb-core. But since it's a minor modification here , we could pragmatically point to the appropriate commit that we want, until we release a gatb-core update.

**Comment by rchikhi** [comment]
@rizkg:

I had added -DUSE_NEW_CXX to MindTheGap CMakefile's. It's odd that you needed to have it defined in gatb-core's CMakefile also, isn't it? Because gatb-core doesn't have any #ifdef USE_NEW_CXX.

I think our politics are to only link to a released version of gatb-core. But since it's a minor modification here , we could pragmatically point to the appropriate commit that we want, until we release a gatb-core update.
